site_name: Syscript

nav:
  - 'Syscript': index.md
  - 'User Guide':
    - Write Sy: write.md
    - Style Sy: style.md
  - License: license.md
  - Todo List: todo.md
  - 'Experimental':
    - Rust Implementation: rust_impl.md

theme:
  name: material
  palette:
    scheme: default
    primary: amber
    accent: orange
